version: "3.3"

services:
  nginx:
    container_name: 'farmplast-service'
    build:
      context: .
      dockerfile: docker/farmplast.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
      - .:/var/www/localhost/htdocs
    networks:
      - app
    restart: always
networks:
  app:
    driver: bridge
